### ISSUE TITLE
unpack(): Type N: not enough input, need 4, have 0

### ISSUE THREAD

**Issue by codezm** [xingwenge/canal-php#20]
报错信息在 canal-php/src/adapter/clue/CanalConnector.php on line 29
我尝试打印 `$data` 变量，值为 ""。

感谢答复~

**Comment by codezm** [comment]
对应 server 端错误信息：
```bash
2020-11-18 15:45:55.445 [New I/O server worker #4-4] ERROR c.a.otter.canal.server.netty.handler.SessionHandler - something goes wrong with channel:[id: 0x0ce74db1, /172.17.0.1:37894 => /172.17.0.2:11111], exception=java.lang.IllegalArgumentException: illegal hex-string: canal
	at com.alibaba.otter.canal.protocol.SecurityUtil.hexStr2Bytes(SecurityUtil.java:237)
	at com.alibaba.otter.canal.server.embedded.CanalServerWithEmbedded.auth(CanalServerWithEmbedded.java:126)
	at com.alibaba.otter.canal.server.netty.handler.ClientAuthenticationHandler.messageReceived(ClientAuthenticationHandler.java:63)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.unfoldAndfireMessageReceived(ReplayingDecoder.java:526)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:507)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:444)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:350)
	at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:281)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:201)
	at org.jboss.netty.util.internal.IoWorkerRunnable.run(IoWorkerRunnable.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

php exception:
`Socket operation failed: No error information`
